3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Models/Image.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ImageSharingWithSecurity.Models
{
    public class Image
        /*
         * Entity model for an image.
         */
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual int Id { get; set; }
        [MaxLength(40)]
        public virtual string Caption { get; set; }
        [MaxLength(200)]
        public virtual string Description { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public virtual DateTime DateTaken { get; set; }

        [ForeignKey("User")]
        public virtual string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        [ForeignKey("Tag")]
        public virtual int TagId { get; set; }
        public virtual Tag Tag { get; set; }

        public virtual bool Approved { get; set; }
    }
}

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Models/ImageView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ImageSharingWithSecurity.Models
{
    public class ImageView
        /*
         * View model for an image.
         */
    {
        [Required]
        [StringLength(40)]
        public String Caption {get; set;}
        [Required]
        public int TagId { get; set; }
        [Required]
        [StringLength(200)]
        public String Description { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}",ApplyFormatInEditMode=true)]
        public DateTime DateTaken { get; set; }

        [ScaffoldColumn(false)]
        // Do not call this Id, it will confuse model binding when posting back to controller
        // because of the default route {controller}/{action}/{?id}
        public int Id;
        [ScaffoldColumn(false)]
        public String TagName { get; set; }
        [ScaffoldColumn(false)]
        public String Username { get; set; }

        public IFormFile ImageFile { get; set; }

        public IEnumerable<SelectListItem> Tags { get; set; }

        public ImageView()
        {
        }
    }
}

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

using ImageSharingWithSecurity.DAL;
using ImageSharingWithSecurity.Models;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace ImageSharingWithSecurity.Controllers
{
    [Authorize]
    public class ImagesController : BaseController
    {
        private readonly IHostingEnvironment hostingEnvironment;

        private readonly ILogger<ImagesController> logger;

        // Dependency injection
        public ImagesController(UserManager<ApplicationUser> userManager,
                                ApplicationDbContext db,
                                IHostingEnvironment environment,
                                ILogger<ImagesController> logger)
            : base(userManager, db)
        {
            this.hostingEnvironment = environment;
            this.logger = logger;
        }

        protected void mkDirectories()
        {
            var dataDir = Path.Combine(hostingEnvironment.WebRootPath,
               "data", "images");
            if (!Directory.Exists(dataDir))
            {
                Directory.CreateDirectory(dataDir);
            }
        }

        protected string imageDataFile(int id)
        {
            return Path.Combine(
               hostingEnvironment.WebRootPath,
               "data", "images", "img-" + id + ".jpg");
        }

        public static string imageContextPath(int id)
        {
            return "data/images/img-" + id + ".jpg";
        }

        [HttpGet]
        public ActionResult Upload()
        {
            CheckAda();
            //String Username = GetLoggedInUser();
            //if (Username == null)
            //{
            //    return ForceLogin();
            //}

            ViewBag.Message = "";
            ImageView imageView = new ImageView();
            imageView.Tags = new SelectList(db.Tags, "Id", "Name", 1);
            return View(imageView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Upload(ImageView imageView)
        {
            CheckAda();

            //String Username = GetLoggedInUser();
            //if (Username == null)
            //{
            //    return ForceLogin();
            //}

            await TryUpdateModelAsync(imageView);

            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Please correct the errors in the form!";
                ViewBag.Tags = new SelectList(db.Tags, "Id", "Name", 1);
                return View();
            }

            ApplicationUser user = await GetLoggedInUser();
            //  User user = db.Users.SingleOrDefault(u => u.Username.Equals(Username));
            //if (user == null)
            //{
            //    ViewBag.Message = "No such Username registered!";
            //    return View();
            //}

            if (imageView.ImageFile == null || imageView.ImageFile.Length <= 0)
            {
                ViewBag.Message = "No image file specified!";
                imageView.Tags = new SelectList(db.Tags, "Id", "Name", 1);
                return View(imageView);
            }

            // TODO save image metadata in the database 
            Image image = new Image();
            image.Caption = imageView.Caption;
            image.TagId = imageView.TagId;
            image.Description = imageView.Description;
            image.DateTaken = imageView.DateTaken;
            image.UserId = user.Id;

            db.Entry(image).State = EntityState.Added;
            db.SaveChanges();
            // end TODO

            mkDirectories();

            // TODO save image file on disk
            await imageView.ImageFile.CopyToAsync(new FileStream(imageDataFile(image.Id), FileMode.Create));
            // end TODO

            return RedirectToAction("Details", new { Id = image.Id });
        }

        [HttpGet]
        public ActionResult Query()
        {
            CheckAda();
            //if (GetLoggedInUser() == null)
            //{
            //    return ForceLogin();
            //}

            ViewBag.Message = "";
            return View();
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            CheckAda();
            //if (GetLoggedInUser() == null)
            //{
            //    return ForceLogin();
            //}

            Image image = db.Images.Find(Id);
            if (image == null)
            {
                return RedirectToAction("Error", "Home", new { ErrId = "Details:" + Id });
            }

            ImageView imageView = new ImageView();
            imageView.Id = image.Id;
            imageView.Caption = image.Caption;
            imageView.Description = image.Description;
            imageView.DateTaken = image.DateTaken;
            /*
             * Eager loading of related entities
             */
            var imageEntry = db.Entry(image);
            imageEntry.Reference(i => i.Tag).Load();
            imageEntry.Reference(i => i.User).Load();
            imageView.TagName = image.Tag.Name;
            imageView.Username = image.User.UserName;
            return View(imageView);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int Id)
        {
            CheckAda();
            ApplicationUser user = await GetLoggedInUser();
            //if (user == null)
            //{
            //    return ForceLogin();
            //}

            Image image = db.Images.Find(Id);
            if (image == null)
            {
                return RedirectToAction("Error", "Home", new { ErrId = "EditNotFound" });
            }

            db.Entry(image).Reference(im => im.User).Load();  // Eager load of user
            if (!image.User.UserName.Equals(user.UserName))
            {
                return RedirectToAction("Error", "Home", new { ErrId = "EditNotAuth" });
            }

            ViewBag.Message = "";

            ImageView imageView = new ImageView();
            imageView.Tags = new SelectList(db.Tags, "Id", "Name", image.TagId);
            imageView.Id = image.Id;
            imageView.TagId = image.TagId;
            imageView.Caption = image.Caption;
            imageView.Description = image.Description;
            imageView.DateTaken = image.DateTaken;

            return View("Edit", imageView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DoEdit(int Id, ImageView imageView)
        {
            CheckAda();
            ApplicationUser user = await GetLoggedInUser();
            //if (user == null)
            //{
            //    return ForceLogin();
            //}

            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Please correct the errors on the page";
                imageView.Id = Id;
                imageView.Tags = new SelectList(db.Tags, "Id", "Name", imageView.TagId);
                return View("Edit", imageView);
            }

            logger.LogDebug("Saving changes to image " + Id);
            Image image = db.Images.Find(Id);
            if (image == null)
            {
                return RedirectToAction("Error", "Home", new { ErrId = "EditNotFound" });
            }

            db.Entry(image).Reference(im => im.User).Load();  // Explicit load of user
            if (!image.User.UserName.Equals(user.UserName))
            {
                return RedirectToAction("Error", "Home", new { ErrId = "EditNotAuth" });
            }

            image.TagId = imageView.TagId;
            image.Caption = imageView.Caption;
            image.Description = imageView.Description;
            image.DateTaken = imageView.DateTaken;
            db.Entry(image).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { Id = Id });
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int Id)
        {
            CheckAda();
            ApplicationUser user = await GetLoggedInUser();
            //if (user == null)
            //{
            //    return ForceLogin();
            //}

            Image image = db.Images.Find(Id);
            if (image == null)
            {
                return RedirectToAction("Error", "Home", new { ErrId = "Delete" });
            }

            db.Entry(image).Reference(im => im.User).Load();  // Explicit load of user
            if (!image.User.UserName.Equals(user.UserName))
            {
                return RedirectToAction("Error", "Home", new { ErrId = "DeleteNotAuth" });
            }

            ImageView imageView = new ImageView();
            imageView.Id = image.Id;
            imageView.Caption = image.Caption;
            imageView.Description = image.Description;
            imageView.DateTaken = image.DateTaken;
            /*
             * Eager loading of related entities
             */
            db.Entry(image).Reference(i => i.Tag).Load();
            imageView.TagName = image.Tag.Name;
            imageView.Username = image.User.UserName;
            return View(imageView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DoDelete(int Id)
        {
            CheckAda();
            ApplicationUser user = await GetLoggedInUser();
            //if (user == null)
            //{
            //    return ForceLogin();
            //}

            Image image = db.Images.Find(Id);
            if (image == null)
            {
                return RedirectToAction("Error", "Home", new { ErrId = "DeleteNotFound" });
            }

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Approve.cshtml
@model ImageSharingWithSecurity.Models.ApproveModel

@{
    ViewData["Title"] = "Approve Images";
}


<h2>@ViewBag.Title</h2>

<form method="post" asp-action="Approve" asp-controller="Images">

    <fieldset>
        <legend>Approve Images</legend>

        <table class="gridTable">
            <tr>
                <th>Image Caption</th>
                <th>Approve</th>
            </tr>

            @for (var i = 0; i < Model.Images.Count(); i++)
            {
                <tr>
                    <td>
                        <input type="hidden" asp-for="Images[i].Value" />
                        @Model.Images[i].Text
                    </td>
                    <td>
                        <input asp-for="Images[i].Selected" />
                    </td>
                </tr>
            }

        </table>

        <p>
            <input type="submit" value="Save Changes" />
        </p>

    </fieldset>

    <p>@ViewBag.Message</p>

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Delete.cshtml
@using ImageSharingWithSecurity.Controllers;

@model ImageSharingWithSecurity.Models.ImageView

@{
    ViewBag.Title = "Delete Image";
}

<h2>@ViewBag.Title</h2>

<form method="post" asp-action="DoDelete" asp-controller="Images">

    <fieldset>
        <legend>Edit Image Information</legend>

        <input asp-for="Id" class="hidden" />

        <p>
            <img src="~/@(ImagesController.imageContextPath(Model.Id))" />
        </p>

        <p>Image id: @Model.Id</p>

        <p>Tag: @Model.TagName</p>

        <p>Caption: @Model.Caption</p>

        <p>
            Description:
            <br />@Model.Description
        </p>

        <p>Date taken: @Model.DateTaken.ToShortDateString()</p>

        <p>Uploader: @Model.Username</p>

        <p>
            <input type="submit" value="Confirm Delete" />
        </p>
    </fieldset>

    <p>@ViewBag.Message</p>
    <p><div class="text-danger" asp-validation-summary="ModelOnly"></div></p>

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Details.cshtml
@using ImageSharingWithSecurity.Controllers

@model ImageSharingWithSecurity.Models.ImageView

@{
    ViewBag.Title = "Image Details";
}

<h2>@ViewBag.Title</h2>

<p><img src="~/@(ImagesController.imageContextPath(Model.Id))" /></p>

<p>Image id: @Model.Id</p>

<p>Tag: @Model.TagName</p>

<p>Caption: @Model.Caption</p>

<p>Description: <br />@Model.Description</p>

<p>Date taken: @Model.DateTaken.ToShortDateString()</p>

<p>Uploader: @Model.Username</p>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Edit.cshtml
@using ImageSharingWithSecurity.Controllers

@model ImageSharingWithSecurity.Models.ImageView

@{
    ViewBag.Title = "Edit Image";
}

<h2>@ViewBag.Title</h2>

<form method="post" asp-action="DoEdit" asp-controller="Images">

    <fieldset>
        <legend>Edit Image Information</legend>

        <input type="hidden" asp-for="Id" />

        <p>
            <img src="~/@(ImagesController.imageContextPath(Model.Id))" />
        </p>

        <p>Image id: @Model.Id</p>

        <p>
            Caption:
            <input asp-for="Caption" placeholder=@Model.Caption />
        </p>
        <p>
            Select a tag:
            <select asp-for="TagId" asp-items="Model.Tags" placeholder=@Model.TagId>
                <option disabled selected value="">Select a tag</option>
            </select>
        </p>
        <p>
            Description:<br />
            <textarea asp-for="Description" cols="60" rows="5"></textarea>
        </p>
        <p>
            Date taken:
            <input asp-for="DateTaken" />
        </p>
        <p>
            <input type="submit" value="Submit Changes" />
        </p>
    </fieldset>

    <p>@ViewBag.Message</p>
    <p><div class="text-danger" asp-validation-summary="ModelOnly"></div></p>

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/ListAll.cshtml
@model IEnumerable<ImageSharingWithSecurity.Models.Image>

@{
    ViewBag.Title = "All Images";
}

<h2>@ViewBag.Title</h2>

<table>
    <tr>
        <th>Caption</th>
        <th>Uploader</th>
        <th>Tag</th>
        <th>Actions</th>
    </tr>

    @foreach (var image in Model)
    {
        <tr>
            <td>
                @image.Caption
            </td>
            <td>
                @image.User.UserName
            </td>
            <td>
                @image.Tag.Name
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@image.Id">Details</a>

                @if (ViewBag.UserName.Equals(image.User.UserName))
                {
                    <text>
                        <!-- TODO add Edit and Delete links -->
                        <a asp-action="Edit" asp-route-id="@image.Id">Edit</a>
                        <a asp-action="Delete" asp-route-id="@image.Id">Delete</a>
                    </text>
                }
            </td>
        </tr>
    }
</table>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/ListByTag.cshtml
@model ImageSharingWithSecurity.Models.ListByTagModel

@{
    ViewBag.Title = "List Images By Tag";
}

<h2>@ViewBag.Title</h2>

<form method="get" asp-action="DoListByTag" asp-controller="Images">

    <fieldset>
        <legend>Choose a tag</legend>
        <p>
            Tag: 
            <select asp-for="Id" asp-items="Model.Tags">
                <option disabled selected value="">Select a tag</option>
            </select>
        </p>
        <p>
            <input type="submit" value="List" />
        </p>
    </fieldset>

    @ViewBag.Message

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/ListByUser.cshtml
@model ImageSharingWithSecurity.Models.ListByUserModel

@{
    ViewBag.Title = "List Images By User";
}

<h2>@ViewBag.Title</h2>

<form method="get" asp-action="DoListByUser" asp-controller="Images">

    <fieldset>
        <legend>Choose a user</legend>
        <p>
            <!-- TODO select user from a drop-down menu -->
            User:
            <select asp-for="Id" asp-items="Model.Users">
                <option disabled selected value="">Select a user</option>
            </select>
        </p>
        <p>
            <input type="submit" value="List" />
        </p>
    </fieldset>

    @ViewBag.Message

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Query.cshtml
@{
    ViewBag.Title = "Find an Image";
}

<

<h2>@ViewBag.Title</h2>

<form method="get" asp-action="Details" asp-controller="Images">

    <fieldset>
        <legend>Enter Image Information</legend>
        <p>
            Image id: <input id="Id" name="Id" type="number"/>
        </p>
        <p>
            <input type="submit" value="Query" />
        </p>
    </fieldset>

    @ViewBag.Message

</form>

3/Assignment3-Code/ImageSharingWithSecurity/ImageSharingWithSecurity/Views/Images/Upload.cshtml
@model ImageSharingWithSecurity.Models.ImageView

@{
    ViewBag.Title = "Upload an Image";
}

<h2>@ViewBag.Title</h2>

<form method="post" asp-action="Upload" asp-controller="Images" enctype="multipart/form-data">


    <fieldset>
        <legend>Enter Image Information</legend>
        <p>
            Caption: <input asp-for="Caption" /><span asp-validation-for="Caption" />
        </p>
        <p>Select a tag: 
            <select asp-for="TagId" asp-items="Model.Tags">
                <option disabled selected value="">Select a tag</option>
            </select>
        </p>
        <p>
            Description:<br />
            <textarea asp-for="Description" cols="40" rows="5">
                Enter description here.
            </textarea>
        </p>
        <p>
            Date taken: <input asp-for="DateTaken" /><span asp-validation-for="DateTaken" />
        </p>
        <p>
            <input asp-for="ImageFile" />
        </p>
        <p>
            <input type="submit" value="Upload" />
        </p>
    </fieldset>

    <p>@ViewBag.Message</p>
    <p><div class="text-danger" asp-validation-summary="ModelOnly"></div></p>

</form>